version: "3.8"
services:
  frontend:
    container_name: frontend
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    networks:
      - common-network # Use the common network
    command: sh -c "npm run db:migrate && npm run drizzle:seed && npm start"

networks:
  common-network:
    name: common-network
    external: true
